[build]
  command = "npm run build"       # or "yarn build"
  functions = "netlify/functions"
  publish = "dist"                # For Vite projects, or "build" for CRA


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
